[tool.poetry]
name = "matrix-loading"
version = "1.0.0"
description = "Exercise 01 - Loading Programs: Matrix data analysis tool"
authors = ["meldemir <meldemir@student.42berlin.de>"]
packages = []

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.0"
numpy = "^1.24.0"
matplotlib = "^3.7.0"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 88